parent_dir = "exp/insurance/ctabgan-plus"
real_data_path = "data/insurance/"
seed = 0
device = "cuda:0"

[train_params]
lr = 0.0016000672327730358
epochs = 10000
class_dim = [
    64,
    64,
    64,
]
batch_size = 856
random_dim = 16
num_channels = 64

[sample]
seed = 0
num_samples = 3600

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
