parent_dir = "exp/buddy/tvae"
real_data_path = "data/buddy/"
seed = 0
device = "cuda:1"

[train_params]
lr = 0.0016961264607506202
epochs = 20000
embedding_dim = 1024
batch_size = 256
loss_factor = 6.998471329724449
compress_dims = [
    256,
    64,
    64,
    256,
]
decompress_dims = [
    256,
    64,
    64,
    256,
]

[sample]
seed = 0
num_samples = 6000

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
