seed = 0
parent_dir = "exp/house/ddpm_mlp_best"
real_data_path = "data/house/"
model_type = "mlp"
num_numerical_features = 16
device = "cuda:1"

[model_params]
d_in = 17
num_classes = 0
is_y_cond = false

[model_params.rtdl_params]
d_layers = [
    1024,
    256,
    256,
    128,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 20000
lr = 0.002990485680629068
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 50400
batch_size = 10000
seed = 0

[eval.type]
eval_model = "mlp"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"
