parent_dir = "exp/higgs-small/smote"
real_data_path = "data/higgs-small/"
seed = 0

[smote_params]
k_neighbours = 14
frac_samples = 8
frac_lam_del = 0.05

[sample]
seed = 0

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
