parent_dir = "exp/buddy/ctabgan-plus"
real_data_path = "data/buddy/"
seed = 0
device = "cuda:0"

[train_params]
lr = 0.0002140849623300361
epochs = 10000
class_dim = [
    64,
    64,
    64,
    128,
]
batch_size = 2048
random_dim = 32
num_channels = 64

[sample]
seed = 0
num_samples = 48000

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
