seed = 0
parent_dir = "exp/california/ddpm_cb_best"
real_data_path = "data/california/"
num_numerical_features = 8
model_type = "mlp"
device = "cuda:3"

[model_params]
d_in = 9
num_classes = 0
is_y_cond = false

[model_params.rtdl_params]
d_layers = [
    512,
    256,
    256,
    256,
    256,
    128,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"

[train.main]
steps = 30000
lr = 0.0013275991211473216
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 4128
batch_size = 4128
seed = 0

[sample.perturb_dict]
tau = 0.5

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
