parent_dir = "exp/miniboone/tvae"
real_data_path = "data/miniboone/"
seed = 0
device = "cuda:1"

[train_params]
lr = 0.000664515187310261
epochs = 30000
embedding_dim = 256
batch_size = 4096
loss_factor = 0.787216940718989
compress_dims = [
    512,
]
decompress_dims = [
    512,
]

[sample]
seed = 0
num_samples = 664000

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
