parent_dir = "exp/california/tvae"
real_data_path = "data/california/"
seed = 0
device = "cuda:1"

[train_params]
lr = 0.0011942868314382704
epochs = 20000
embedding_dim = 128
batch_size = 256
loss_factor = 3.3878447780232825
compress_dims = [
    512,
    512,
    512,
    512,
]
decompress_dims = [
    512,
    512,
    512,
    512,
]

[sample]
seed = 0
num_samples = 26400

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
