parent_dir = "exp/churn2/tvae"
real_data_path = "data/churn2/"
seed = 0
device = "cuda:1"

[train_params]
lr = 0.00047756638508070437
epochs = 30000
embedding_dim = 256
batch_size = 256
loss_factor = 2.4301590023300905
compress_dims = [
    256,
    512,
]
decompress_dims = [
    256,
    512,
]

[sample]
seed = 0
num_samples = 52000

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
