parent_dir = "exp/wilt/ctabgan-plus"
real_data_path = "data/wilt/"
seed = 0
device = "cuda:1"

[train_params]
lr = 0.0002993957976860954
epochs = 10000
class_dim = [
    128,
    256,
    128,
]
batch_size = 512
random_dim = 32
num_channels = 64

[sample]
seed = 0
num_samples = 12400

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
