seed = 0
parent_dir = "./ckpt/inf_10000_twin_2"
real_data_path = "/home/liu00980/Documents/multimodal/tabular/tab-ddpm/data/inf_raw_twin_2"
num_numerical_features = 8
model_type = "mlp"
device = "cuda:5"

[model_params]
d_in = 9
num_classes = 0
is_y_cond = false

[model_params.rtdl_params]
d_layers = [
    512,
    256,
    256,
    256,
    256,
    128,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"

[train.main]
steps = 1000
lr = 3e-06
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 1000
batch_size = 1000
seed = 0

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
