parent_dir = "exp/higgs-small/ctabgan"
real_data_path = "data/higgs-small/"
seed = 0
device = "cuda:1"

[train_params]
lr = 0.0005772589953788761
epochs = 5000
class_dim = [
    256,
    128,
    128,
    128,
]
batch_size = 2048
random_dim = 128
num_channels = 64

[sample]
seed = 0
num_samples = 125400

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
