seed = 0
parent_dir = "exp/ad21/many-exps/2"
real_data_path = "data/ad21/"
model_type = "mlp"
num_numerical_features = 20
device = "cuda:0"

[model_params]
d_in = 17
num_classes = 0
is_y_cond = false

[model_params.rtdl_params]
d_layers = [
    1024,
    512,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 1000
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 5000
lr = 0.00038473523622807365
weight_decay = 0.0
batch_size = 256

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 332
batch_size = 10000
seed = 4

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
