parent_dir = "exp/higgs-small/tvae"
real_data_path = "data/higgs-small/"
seed = 0
device = "cuda:0"

[train_params]
lr = 0.0003106059409975757
epochs = 30000
embedding_dim = 128
batch_size = 4096
loss_factor = 6.425117768649489
compress_dims = [
    256,
    512,
    512,
    512,
]
decompress_dims = [
    256,
    512,
    512,
    512,
]

[sample]
seed = 0
num_samples = 31500

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
