parent_dir = "exp/king/ctabgan-plus"
real_data_path = "data/king/"
seed = 0
device = "cuda:0"

[train_params]
lr = 0.0006772380448845386
epochs = 10000
class_dim = [
    128,
    256,
    256,
    256,
]
batch_size = 1024
random_dim = 16
num_channels = 64

[sample]
seed = 0
num_samples = 110400

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
