parent_dir = "exp/wilt/ctabgan"
real_data_path = "data/wilt/"
seed = 0
device = "cuda:1"

[train_params]
lr = 0.0012825908944717134
epochs = 5000
class_dim = [
    512,
    128,
    128,
    512,
]
batch_size = 2048
random_dim = 128
num_channels = 64

[sample]
seed = 0
num_samples = 24800

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
