parent_dir = "exp/diabetes/smote"
real_data_path = "data/diabetes/"
seed = 0

[smote_params]
k_neighbours = 8
frac_samples = 0.25
frac_lam_del = 0.15000000000000002

[sample]
seed = 0

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
