seed = 0
parent_dir = "exp/diabetes/ddpm_mlp_best"
real_data_path = "data/diabetes/"
model_type = "mlp"
num_numerical_features = 8
device = "cuda:0"

[model_params]
d_in = 8
num_classes = 2
is_y_cond = true

[model_params.rtdl_params]
d_layers = [
    256,
    256,
    256,
    256,
    256,
    256,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 100
gaussian_loss_type = "mse"

[train.main]
steps = 30000
lr = 1.5402178626529827e-05
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 1000
batch_size = 10000
seed = 0

[eval.type]
eval_model = "mlp"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "one-hot"
y_policy = "default"
