seed = 0
parent_dir = "exp/insurance/ddpm_cb_best"
real_data_path = "data/insurance/"
num_numerical_features = 3
model_type = "mlp"
device = "cuda:6"

[model_params]
d_in = 12
num_classes = 0
is_y_cond = false

[model_params.rtdl_params]
d_layers = [
    256,
    512,
    512,
    512,
    512,
    256,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 100
gaussian_loss_type = "mse"
scheduler = "cosine"

[train.main]
steps = 30000
lr = 0.0011121628249569867
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 268
batch_size = 268
seed = 0

[sample.perturb_dict]
tau = 0.5

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"
model = "catboost"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
