seed = 0
parent_dir = "exp/abalone/ddpm_cb_best"
real_data_path = "data/abalone/"
model_type = "mlp"
num_numerical_features = 7
device = "cuda:4"

[model_params]
is_y_cond = false
d_in = 11
num_classes = 0

[model_params.rtdl_params]
d_layers = [
    512,
    128,
]
dropout = 0.0

[diffusion_params]
num_timesteps = 100
gaussian_loss_type = "mse"

[train.main]
steps = 30000
lr = 0.0003442062504112041
weight_decay = 0.0
batch_size = 4096

[train.T]
seed = 0
normalization = "quantile"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"

[sample]
num_samples = 836
batch_size = 836
seed = 0

[sample.perturb_dict]
tau = 0.5

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
