parent_dir = "exp/churn2/ctabgan"
real_data_path = "data/churn2/"
seed = 0
device = "cuda:1"

[train_params]
lr = 0.0003218899030093514
epochs = 10000
class_dim = [
    512,
    64,
]
batch_size = 1024
random_dim = 128
num_channels = 64

[sample]
seed = 0
num_samples = 52000

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
