parent_dir = "exp/gesture/ctabgan-plus"
real_data_path = "data/gesture/"
seed = 0
device = "cuda:0"

[train_params]
lr = 0.000806922832292031
epochs = 10000
class_dim = [
    64,
    64,
    64,
    64,
]
batch_size = 2048
random_dim = 16
num_channels = 32

[sample]
seed = 0
num_samples = 25200

[eval.type]
eval_model = "catboost"
eval_type = "synthetic"

[eval.T]
seed = 0
normalization = "__none__"
num_nan_policy = "__none__"
cat_nan_policy = "__none__"
cat_min_frequency = "__none__"
cat_encoding = "__none__"
y_policy = "default"
